apiVersion: v1
kind: ConfigMap
metadata:
  name: mf-minio-config
  namespace: argo
data:

  METAFLOW_DEFAULT_DATASTORE: "s3"
  METAFLOW_DATASTORE_SYSROOT_S3: "s3://metaflow"
  METAFLOW_S3_ENDPOINT_URL: "http://minio.minio.svc.cluster.local:9000"
  METAFLOW_S3_VERIFY_CERTIFICATE: "0"


  METAFLOW_DEFAULT_METADATA: "service"
  METAFLOW_SERVICE_URL: "http://metaflow-metaflow-service.metaflow.svc.cluster.local:8080"
